ALTER TABLE "users"
  ADD COLUMN IF NOT EXISTS "createdat" TIMESTAMP(6),
  ADD COLUMN IF NOT EXISTS "updatedat" TIMESTAMP(6);

UPDATE "users"
SET
  "createdat" = COALESCE("createdat", CURRENT_TIMESTAMP),
  "updatedat" = COALESCE("updatedat", CURRENT_TIMESTAMP);

ALTER TABLE "users"
  ALTER COLUMN "createdat" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "createdat" SET NOT NULL,
  ALTER COLUMN "updatedat" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedat" SET NOT NULL;