DROP TABLE IF EXISTS BookGenre CASCADE;
DROP TABLE IF EXISTS BookAuthor CASCADE;
DROP TABLE IF EXISTS Review CASCADE;
DROP TABLE IF EXISTS Rating CASCADE;
DROP TABLE IF EXISTS Book CASCADE;
DROP TABLE IF EXISTS Genre CASCADE;
DROP TABLE IF EXISTS Author CASCADE;
DROP TABLE IF EXISTS Publisher CASCADE;
DROP TABLE IF EXISTS Users CASCADE;

CREATE TABLE IF NOT EXISTS Users (
    UserID SERIAL PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE CHECK (Email LIKE '%@%'),
    Password VARCHAR(255) NOT NULL,
    Nickname VARCHAR(50),
    AvatarURL TEXT
);

CREATE TABLE IF NOT EXISTS Publisher (
    PublisherID SERIAL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Country VARCHAR(50),
    Website TEXT,
    FoundedYear INT CHECK (FoundedYear >= 1450 AND FoundedYear <= EXTRACT(YEAR FROM CURRENT_DATE))
);

CREATE TABLE IF NOT EXISTS Author (
    AuthorID SERIAL PRIMARY KEY,
    FullName VARCHAR(100) NOT NULL,
    Country VARCHAR(50),
    BirthDate DATE,
    DeathDate DATE CHECK (DeathDate IS NULL OR DeathDate >= BirthDate),
    PhotoURL TEXT,
    Biography TEXT
);

CREATE TABLE IF NOT EXISTS Genre (
    GenreID SERIAL PRIMARY KEY,
    Name VARCHAR(50) NOT NULL UNIQUE,
    Description TEXT
);

CREATE TABLE IF NOT EXISTS Book (
    BookID SERIAL PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    ISBN VARCHAR(17) UNIQUE,
    PublicationDate DATE,
    Description TEXT,
    PageCount INT CHECK (PageCount > 0),
    Language VARCHAR(50) NOT NULL DEFAULT 'English',
    CoverURL TEXT,
    PublisherID INT REFERENCES Publisher(PublisherID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Rating (
    RatingID SERIAL PRIMARY KEY,
    UserID INT NOT NULL REFERENCES Users(UserID) ON DELETE CASCADE,
    BookID INT NOT NULL REFERENCES Book(BookID) ON DELETE CASCADE,
    Score NUMERIC(2,1) NOT NULL CHECK (Score >= 1.0 AND Score <= 5.0),
    UNIQUE(UserID, BookID)
);

CREATE TABLE IF NOT EXISTS Review (
    ReviewID SERIAL PRIMARY KEY,
    UserID INT NOT NULL REFERENCES Users(UserID) ON DELETE CASCADE,
    BookID INT NOT NULL REFERENCES Book(BookID) ON DELETE CASCADE,
    ReviewText TEXT NOT NULL CHECK (LENGTH(ReviewText) BETWEEN 10 AND 5000),
    ReviewDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LastEditDate TIMESTAMP,
    UNIQUE(UserID, BookID)
);

CREATE TABLE IF NOT EXISTS BookAuthor (
    BookID INT NOT NULL REFERENCES Book(BookID) ON DELETE CASCADE,
    AuthorID INT NOT NULL REFERENCES Author(AuthorID) ON DELETE CASCADE,
    AuthorOrder INT NOT NULL CHECK (AuthorOrder > 0),
    PRIMARY KEY (BookID, AuthorID)
);

CREATE TABLE IF NOT EXISTS BookGenre (
    BookID INT NOT NULL REFERENCES Book(BookID) ON DELETE CASCADE,
    GenreID INT NOT NULL REFERENCES Genre(GenreID) ON DELETE CASCADE,
    PRIMARY KEY (BookID, GenreID)
);



